// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKWVa2loRNIhjDv07_mpNYKHglVPmTXUU',
    appId: '1:142448075308:web:4a91b8b0faef38548ca789',
    messagingSenderId: '142448075308',
    projectId: 'dsltechbank',
    authDomain: 'dsltechbank.firebaseapp.com',
    storageBucket: 'dsltechbank.firebasestorage.app',
    measurementId: 'G-Z0M4WBG2JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnKqcsIxDKsWc8gn2fYvXmfQQRqQ640Gc',
    appId: '1:142448075308:android:580e996f77f34e298ca789',
    messagingSenderId: '142448075308',
    projectId: 'dsltechbank',
    storageBucket: 'dsltechbank.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Qcw3TZkxTPiIBRk4N1QPweiSw81HR78',
    appId: '1:142448075308:ios:30c165c22b4675b68ca789',
    messagingSenderId: '142448075308',
    projectId: 'dsltechbank',
    storageBucket: 'dsltechbank.firebasestorage.app',
    iosBundleId: 'tech.dsl.finlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Qcw3TZkxTPiIBRk4N1QPweiSw81HR78',
    appId: '1:142448075308:ios:30c165c22b4675b68ca789',
    messagingSenderId: '142448075308',
    projectId: 'dsltechbank',
    storageBucket: 'dsltechbank.firebasestorage.app',
    iosBundleId: 'tech.dsl.finlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKWVa2loRNIhjDv07_mpNYKHglVPmTXUU',
    appId: '1:142448075308:web:8e8bfe963535fb428ca789',
    messagingSenderId: '142448075308',
    projectId: 'dsltechbank',
    authDomain: 'dsltechbank.firebaseapp.com',
    storageBucket: 'dsltechbank.firebasestorage.app',
    measurementId: 'G-2QYPL3RYYN',
  );
}
